// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0F6m-iDg7b65C3xqwIgYBgPd5taKF4A4',
    appId: '1:718020299821:web:2f35f287e1ac4bdbd0bca4',
    messagingSenderId: '718020299821',
    projectId: 'evently-5934d',
    authDomain: 'evently-5934d.firebaseapp.com',
    storageBucket: 'evently-5934d.firebasestorage.app',
    measurementId: 'G-ENCX87EMP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ2KWYs7p5VvgDxzjsq0o3Y5eqIfPznZ4',
    appId: '1:718020299821:android:fd1611edaf2fc598d0bca4',
    messagingSenderId: '718020299821',
    projectId: 'evently-5934d',
    storageBucket: 'evently-5934d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATgDAg3QfS_tAn0Rawaj6qTscYoF5I9tQ',
    appId: '1:718020299821:ios:70cf9c015255ebccd0bca4',
    messagingSenderId: '718020299821',
    projectId: 'evently-5934d',
    storageBucket: 'evently-5934d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATgDAg3QfS_tAn0Rawaj6qTscYoF5I9tQ',
    appId: '1:718020299821:ios:70cf9c015255ebccd0bca4',
    messagingSenderId: '718020299821',
    projectId: 'evently-5934d',
    storageBucket: 'evently-5934d.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0F6m-iDg7b65C3xqwIgYBgPd5taKF4A4',
    appId: '1:718020299821:web:0c81e056268be4f9d0bca4',
    messagingSenderId: '718020299821',
    projectId: 'evently-5934d',
    authDomain: 'evently-5934d.firebaseapp.com',
    storageBucket: 'evently-5934d.firebasestorage.app',
    measurementId: 'G-H49T2F1PZY',
  );

}